import type { MapConfig } from "@monopoly/shared";
import {
  corner,
  property,
  railroad,
  utility,
  tax,
  surprise,
  treasure,
  defaultDecks,
} from "./_helpers.js";

/**
 * 🇵🇰 Pakistan — cities of Pakistan on the classic 40-tile ring (README §6).
 * A template for how new maps are made: same engine, different data.
 */
export const pakistan: MapConfig = {
  id: "pakistan",
  name: "Pakistan",
  theme: "pakistan",
  currency: "₨",
  tiles: [
    corner(0, "start", "Start"),
    property(1, "Gwadar", "brown", 60),
    treasure(2),
    property(3, "Turbat", "brown", 60),
    tax(4, "Income Tax", 200),
    railroad(5, "Jinnah Intl (KHI)"),
    property(6, "Peshawar", "lightblue", 100),
    surprise(7),
    property(8, "Quetta", "lightblue", 100),
    property(9, "Multan", "lightblue", 120),
    corner(10, "jail", "In Prison"),
    property(11, "Sukkur", "pink", 120),
    utility(12, "WAPDA"),
    property(13, "Hyderabad", "pink", 140),
    property(14, "Sialkot", "pink", 140),
    railroad(15, "Allama Iqbal (LHE)"),
    property(16, "Faisalabad", "orange", 160),
    treasure(17),
    property(18, "Rawalpindi", "orange", 160),
    property(19, "Gujranwala", "orange", 180),
    corner(20, "vacation", "Vacation"),
    property(21, "Abbottabad", "red", 180),
    surprise(22),
    property(23, "Murree", "red", 200),
    property(24, "Bahawalpur", "red", 220),
    railroad(25, "Islamabad Intl (ISB)"),
    property(26, "Mardan", "yellow", 220),
    property(27, "Sargodha", "yellow", 220),
    utility(28, "K-Electric"),
    property(29, "Sahiwal", "yellow", 240),
    corner(30, "goto_jail", "Go To Prison"),
    property(31, "Islamabad", "green", 260),
    property(32, "Lahore (Gulberg)", "green", 280),
    treasure(33),
    property(34, "Lahore (DHA)", "green", 300),
    railroad(35, "Multan Intl (MUX)"),
    surprise(36),
    property(37, "Karachi (Clifton)", "darkblue", 350),
    tax(38, "FBR Levy", 100),
    property(39, "Karachi (DHA)", "darkblue", 400),
  ],
  decks: defaultDecks(),
};
